<%

' WARNING: DO NOT EDIT THIS FILE.
' This file is automatically generated by the Zoom Indexer application
' and will be updated each time you re-index your site. You should make all
' setting changes directly from the Indexer, via the Configuration window.
' 
' If you wish to modify the text messages such as "Search results for...",
' etc. then look up "Zoom Language Files" or "Translating the search page"
' in the Users Guide for information.

UseUTF8 = 0
Charset = "windows-1252"
Codepage = 1252
UseStemming = 0
NoCharset = 1
MapAccents = 0
MinWordLen = 2
Highlighting = 1
GotoHighlight = 1
PdfHighlight = 1
FormFormat = 2
Logging = 1
LogFileName = "searchwords.log"
MaxKeyWordLineLen = 256
OutputBasewordBufferSize = 19387
OutputVariantBufferSize = 6349
DictIDLen = 3
NumKeywords = 2044
NumVariants = 496
NumPages = 79
PageInfoSize = 1343
MaxMatches = 1000
MaxContextSeeks = 500
MaxSearchTime = 30
DictReservedLimit = 165
DictReservedSuffixes = 83
DictReservedPrefixes = 124
DictReservedNoSpaces = 165
WordSplit = 1
ZoomInfo = 0
Timing = 0
DefaultToAnd = 0
SearchAsSubstring = 0
ToLowerSearchWords = 1
StripDiacritics = 0
ContextSize = 30
MaxContextKeywords = 3
WeightProximity = 0
AllowExactPhrase = 1
UseLinkTarget = 0
UseDateTime = 1
UseZoomImage = 0
WordJoinChars = ".-_'"
Spelling = 1
SpellingWhenLessThan = 5
NumSpellings = 1062
Recommended = 0
NumRecommended = 0
RecommendedMax = 0
UseCats = 0
UseMetaFields = 0
NumMetaFields = 0
DisplayMetaFields = 0
LinkBackURL = "MainSearch.asp"
TruncateShowURL = 0
DisplayNumber = 1
DisplayTitle = 1
DisplayMetaDesc = 1
DisplayContext = 1
DisplayTerms = 1
DisplayScore = 1
DisplayURL = 1
DisplayDate = 1
DisplayFilesize = 0
StartPtFailed = 0
Version = "Version 6.0 (1028) PRO"
STR_FORM_SEARCHFOR = "Zoek naar:"
STR_FORM_SUBMIT_BUTTON = "Verzend"
STR_FORM_RESULTS_PER_PAGE = "Resultaten per pagina:"
STR_FORM_CATEGORY = "Categorie:"
STR_FORM_CATEGORY_ALL = "Alle"
STR_FORM_MATCH = "Overeenkomsten:"
STR_FORM_ANY_SEARCH_WORDS = "ieder trefwoord"
STR_FORM_ALL_SEARCH_WORDS = "alle trefwoorden"
STR_NO_QUERY = "Geen trefwoorden ingevoerd."
STR_RESULTS_FOR = "Gevonden resultaten voor:"
STR_RESULTS_IN_ALL_CATEGORIES = "in alle categorieën"
STR_RESULTS_IN_CATEGORY = "in categorie"
STR_POWEREDBY = "Zoekmachine gebruikt van"
STR_NO_RESULTS = "Geen resultaten"
STR_RESULT = "resultaat"
STR_RESULTS = "resultaten"
STR_PHRASE_CONTAINS_COMMON_WORDS = "De volgende zin bevat vrij vaak in deze website gebruikte woorden. Het resultaat is dat er teveel zoekresultaten getoond worden. Geef a.u.b. een meer verfijnde zoekvraag voor betere resultaten."
STR_SKIPPED_FOLLOWING_WORDS = "De (Het) volgende woord(en) worden overgeslagen:"
STR_SKIPPED_PHRASE = "Opgelet: U kunt geen zoekvraag beginnen met een woord welke overgeslagen wordt."
STR_SUMMARY_NO_RESULTS_FOUND = "Geen resultaten gevonden."
STR_SUMMARY_FOUND_CONTAINING_ALL_TERMS = "Gevonden, bevattend alle trefwoorden."
STR_SUMMARY_FOUND_CONTAINING_SOME_TERMS = "Gevonden, bevattend enkele trefwoorden."
STR_SUMMARY_FOUND = "Gevonden."
STR_PAGES_OF_RESULTS = "Pagina's met resultaten."
STR_MORETHAN = "More than"
STR_POSSIBLY_GET_MORE_RESULTS = "U krijgt waarschijnlijk meer, en/of betere, resultaten als u zoekt op"
STR_ANY_OF_TERMS = "ieder trefwoord apart"
STR_ALL_CATS = "alle categorieën"
STR_CAT_SUMMARY = "Refine your search by category:"
STR_DIDYOUMEAN = "Bedoelt u misschien:"
STR_OR = "or"
STR_RECOMMENDED = "Recommended links"
STR_SORTEDBY_RELEVANCE = "Gesorteerd op relevantie"
STR_SORTBY_RELEVANCE = "Gesorteerd op relevantie"
STR_SORTBY_DATE = "Gesorteerd op datum"
STR_SORTEDBY_DATE = "Gesorteerd op datum"
STR_RESULT_TERMS_MATCHED = "trefwoorden komen overeen: "
STR_RESULT_SCORE = "Score: "
STR_RESULT_URL = "URL:"
STR_RESULT_PAGES = "Pagina's met resultaten:"
STR_RESULT_PAGES_PREVIOUS = "Vorige"
STR_RESULT_PAGES_NEXT = "Volgende"
STR_SEARCH_TOOK = "Het zoeken kostte"
STR_SECONDS = "seconden"
STR_MAX_RESULTS = "You have requested more results than served per query. Please try again with a more precise query."
%>
